function [fitresult, gof] = createFit(giorno_anno, giorno_settimana, misura)
%CREATEFIT(GIORNO_ANNO,GIORNO_SETTIMANA,MISURA)
%  Create a fit.
%
%  Data for 'model' fit:
%      X Input : giorno_anno
%      Y Input : giorno_settimana
%      Z Output: misura
%      Weights : giorno_anno
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Apr-2019 10:30:33


%% Fit: 'model'.
[xData, yData, zData, weights] = prepareSurfaceData( giorno_anno, giorno_settimana, misura, giorno_anno );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Span = 0.2;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'model' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'model', 'misura vs. giorno_anno, giorno_settimana with giorno_anno', 'Location', 'NorthEast' );
% Label axes
xlabel giorno_anno
ylabel giorno_settimana
zlabel misura
grid on
view( -5.5, 20.4 );


